set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'davidhalter/jedi-vim'
Plugin 'scrooloose/nerdtree'
Plugin 'nvie/vim-flake8'
Plugin 'altercation/vim-colors-solarized'

call vundle#end() 

filetype plugin indent on

set autoindent
set tabstop=4
set expandtab
set shiftwidth=4
set softtabstop=4
set hlsearch

syntax enable
set background=dark
colorscheme solarized

map <C-n> :NERDTreeToggle<CR>
let NERDTreeIgnore = ['\.pyc$']

autocmd BufWritePost *.py call Flake8()

highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%99v.\+/
